# SafePrice Simulator

### Import Libraries

In [72]:
import os
from datetime import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Reading Raw Datasets

In [73]:
root_path = os.path.dirname(os.getcwd())

raw_data_path = os.path.join(root_path, "datasets/raw")
raw_datasets = os.listdir(raw_data_path)

print(raw_datasets)

['online_retail_II.xlsx', 'Retail Prices Index.xlsx']

#### Read Retail Dateset

In [74]:
online_retail_df_2009_2010 = pd.read_excel(os.path.join(raw_data_path, raw_datasets[0]), sheet_name='year_2009_2010')

online_retail_df_2009_2010.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [75]:
online_retail_df_2010_2011 = pd.read_excel(os.path.join(raw_data_path, raw_datasets[0]), sheet_name='year_2010_2011')

online_retail_df_2010_2011.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [76]:
retail_df = pd.concat([online_retail_df_2009_2010, online_retail_df_2010_2011], ignore_index=True)
retail_df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [77]:
print("2009-2010 dataset lenght: ",len(online_retail_df_2009_2010))
print("2010-2011 dataset lenght: ",len(online_retail_df_2010_2011))
print("Combine Dataset length: ", len(retail_df))

2009-2010 dataset lenght:  525461
2010-2011 dataset lenght:  541910
Combine Dataset length:  1067371

#### Read Retail Prices Index Dateset

In [78]:
retail_price_index_df = pd.read_excel(os.path.join(raw_data_path, raw_datasets[1])).iloc[972:1008]
retail_price_index_df.head()

        Title Retail Prices Index: Long run series: 1800 to 2024: Jan 1974=100
972  2009 JAN                                              828.8
973  2009 FEB                                                834
974  2009 MAR                                              833.6
975  2009 APR                                              834.4
976  2009 MAY                                              839.5

In [79]:
retail_price_index_df.rename(columns={
    'Title': 'Date',
    'Retail Prices Index: Long run series: 1800 to 2024: Jan 1974=100': 'Retail Price Index'
}, inplace=True)

In [80]:
retail_price_index_df.head()

         Date Retail Price Index
972  2009 JAN              828.8
973  2009 FEB                834
974  2009 MAR              833.6
975  2009 APR              834.4
976  2009 MAY              839.5

### Data Preparation

#### Retail DataFrame

In [81]:
retail_df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

##### Filter only UK data

In [82]:
retail_df.Country.unique()

<StringArray>
[      'United Kingdom',               'France',                  'USA',
              'Belgium',            'Australia',                 'EIRE',
              'Germany',             'Portugal',                'Japan',
              'Denmark',              'Nigeria',          'Netherlands',
               'Poland',                'Spain',      'Channel Islands',
                'Italy',               'Cyprus',               'Greece',
               'Norway',              'Austria',               'Sweden',
 'United Arab Emirates',              'Finland',          'Switzerland',
          'Unspecified',                'Malta',              'Bahrain',
                  'RSA',              'Bermuda',            'Hong Kong',
            'Singapore',             'Thailand',               'Israel',
            'Lithuania',          'West Indies',              'Lebanon',
                'Korea',               'Brazil',               'Canada',
              'Iceland',         'Saudi Arabia',       'Czech Republic',
   'European Community']
Length: 43, dtype: str

In [83]:
retail_df = retail_df[retail_df['Country']=='United Kingdom']

In [84]:
retail_df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    240029
Country             0
dtype: int64

##### Exporting Cleaned Dataset

In [85]:
cleaned_data_path = os.path.join(root_path, "datasets/cleaned")
retail_df.to_csv(os.path.join(cleaned_data_path, "retail_cleaned.csv"))

##### Filtered the retail_df

In [86]:
retail_df_filter = retail_df.drop(['Invoice', 'Description', 'Customer ID', 'Country'], axis=1)
retail_df_filter.head()

  StockCode  Quantity         InvoiceDate  Price
0     85048        12 2009-12-01 07:45:00   6.95
1    79323P        12 2009-12-01 07:45:00   6.75
2    79323W        12 2009-12-01 07:45:00   6.75
3     22041        48 2009-12-01 07:45:00   2.10
4     21232        24 2009-12-01 07:45:00   1.25

##### Date Col Formatting

In [87]:
retail_df_filter['InvoiceDate'] = pd.to_datetime(retail_df_filter['InvoiceDate'])
retail_df_filter['InvoiceDate'] = retail_df_filter['InvoiceDate'].dt.to_period('M')

In [88]:
retail_df_filter.head()

  StockCode  Quantity InvoiceDate  Price
0     85048        12     2009-12   6.95
1    79323P        12     2009-12   6.75
2    79323W        12     2009-12   6.75
3     22041        48     2009-12   2.10
4     21232        24     2009-12   1.25

In [89]:
retail_df_filter.dtypes

StockCode         object
Quantity           int64
InvoiceDate    period[M]
Price            float64
dtype: object

#### Retail Prices Index DataFrame

##### Exporting Cleaned Datasets

In [90]:
retail_price_index_df = retail_price_index_df.reset_index(drop=True)
retail_price_index_df.to_csv(os.path.join(cleaned_data_path, "retail_price_index_cleaned.csv"))

##### Date Col Formatting

In [91]:
retail_price_index_df.dtypes

Date                     str
Retail Price Index    object
dtype: object

In [93]:
retail_price_index_df.head()

       Date Retail Price Index
0  2009 JAN              828.8
1  2009 FEB                834
2  2009 MAR              833.6
3  2009 APR              834.4
4  2009 MAY              839.5

In [96]:
retail_price_index_df.Date = pd.to_datetime(retail_price_index_df['Date'], format='mixed')
retail_price_index_df.Date = retail_price_index_df['Date'].dt.to_period()

In [97]:
retail_price_index_df.dtypes

Date                  period[M]
Retail Price Index       object
dtype: object

In [98]:
retail_price_index_df.head()

      Date Retail Price Index
0  2009-01              828.8
1  2009-02                834
2  2009-03              833.6
3  2009-04              834.4
4  2009-05              839.5

#### Merge Two DataFrames

In [107]:
retail_df_final = retail_df_filter.merge(retail_price_index_df, how='left', left_on='InvoiceDate', right_on='Date').drop(['Date'], axis=1)
retail_df_final.tail()

       StockCode  Quantity InvoiceDate  Price Retail Price Index
981325     22466        12     2011-12   1.95              944.4
981326     22061         8     2011-12   2.95              944.4
981327     23275        24     2011-12   1.25              944.4
981328     21217        24     2011-12   8.95              944.4
981329     20685        10     2011-12   7.08              944.4